import {
  CleanupRunner,
  applyAndWaitCrPaths,
  cleanupRenderedArtifacts,
  createNameBuilder,
  destroyFixtureResources,
  ensureDefaultGroup,
  initE2e,
  type E2EApi,
  type FixtureResourceInput,
} from '../..';
import { LOCAL_RENDER_APPLY_TEST_TIMEOUT_MS } from '../../src/test-constants';

const CODEOWNERS_FILE_PATH = '.github/CODEOWNERS';
const CODEOWNERS_READ_RETRY_ATTEMPTS = 12;
const CODEOWNERS_READ_RETRY_DELAY_MS = 5000;

function formatCodeownersLine(path: string, owners: string[]): string {
  return `${path.padEnd(25)} ${owners.join(' ')}`;
}

function buildExpectedCodeowners(
  org: string,
  ownerGroupName: string,
  platformGroupName: string,
): string {
  return [
    '# This file was generated by firestartr.',
    "# WARNING: Please don't edit this file directly in the repository",
    '# Go to gitops repository to modify it!',
    formatCodeownersLine('*', [
      `@${org}/${ownerGroupName}`,
      `@${org}/${platformGroupName}`,
    ]),
    formatCodeownersLine('/.github/', [
      `@${org}/${platformGroupName}`,
      `@${org}/${ownerGroupName}`,
    ]),
    formatCodeownersLine('custom/**', [
      `@${org}/${platformGroupName}`,
      `@${org}/${ownerGroupName}`,
    ]),
  ].join('\n');
}

async function readCodeownersFile(
  client: E2EApi,
  repoName: string,
): Promise<string> {
  return client.gh.getRepoFile(repoName, CODEOWNERS_FILE_PATH, {
    attempts: CODEOWNERS_READ_RETRY_ATTEMPTS,
    delayMs: CODEOWNERS_READ_RETRY_DELAY_MS,
  });
}

// Render the smallest valid component setup, apply it, and assert the remote
// CODEOWNERS file collapses duplicate paths into one merged line per path.
describe('Claim Render Local Component CODEOWNERS E2E', () => {
  let client: E2EApi;
  let fixtures: FixtureResourceInput[] = [];
  let platformGroupName = '';
  let componentName = '';

  beforeAll(async () => {
    client = await initE2e(undefined, undefined, {
      namePrefix: 'component-codeowners',
      onlyFiles: ['firestartr', 'group_a', 'component_a'],
    });

    const nameBuilder = createNameBuilder(client.getPrefix());
    const defaultGroupName = nameBuilder.build('default-group');
    platformGroupName = nameBuilder.build('group-a');
    componentName = nameBuilder.build('component-a');

    fixtures = [
      { fixtureName: 'firestartr', claimName: defaultGroupName },
      'group-a',
      'component-a',
    ];

    await destroyFixtureResources(client, client.getPrefix(), fixtures, {
      logPrefix: 'component-codeowners',
      strict: true,
    });
  }, LOCAL_RENDER_APPLY_TEST_TIMEOUT_MS);

  afterAll(async () => {
    if (!client) {
      return;
    }

    const cleanup = new CleanupRunner();

    await cleanup.run('destroy component fixture resources', async () => {
      await destroyFixtureResources(client, client.getPrefix(), fixtures, {
        logPrefix: 'component-codeowners-afterall',
        strict: true,
      });
    });

    await cleanup.run('cleanup rendered artifacts', async () => {
      await cleanupRenderedArtifacts(client);
    });

    cleanup.warnOnErrors('component-codeowners', 'afterAll');
  }, LOCAL_RENDER_APPLY_TEST_TIMEOUT_MS);

  it(
    'should create the expected CODEOWNERS file for a rendered component',
    async () => {
      // Create the two group dependencies the component CODEOWNERS references.
      const defaultGroup = await ensureDefaultGroup(client);
      const platformGroupRef = `group:${platformGroupName}`;

      const renderedPlatformGroup = await client.claims.renderLocally(
        'group-a',
        {
          patches: [{ op: 'replace', path: '/members', value: [] }],
        },
      );

      await applyAndWaitCrPaths(client, renderedPlatformGroup.crPaths);

      const renderedComponent = await client.claims.renderLocally(
        'component-a',
        {
          patches: [
            { op: 'remove', path: '/system' },
            { op: 'replace', path: '/owner', value: defaultGroup.ref },
            { op: 'replace', path: '/platformOwner', value: platformGroupRef },
            { op: 'remove', path: '/maintainedBy' },
            {
              op: 'replace',
              path: '/providers/github/additionalRules',
              value: [],
            },
            {
              op: 'replace',
              path: '/providers/github/overrides/additionalAdmins',
              value: [],
            },
            {
              op: 'replace',
              path: '/providers/github/overrides/additionalCodeownersRules',
              value: [
                {
                  path: '*',
                  owners: [defaultGroup.ref, platformGroupRef],
                },
                {
                  path: '/.github/',
                  owners: [defaultGroup.ref],
                },
                {
                  path: 'custom/**',
                  owners: [platformGroupRef],
                },
                {
                  path: 'custom/**',
                  owners: [defaultGroup.ref],
                },
                {
                  path: 'custom/**',
                  owners: [defaultGroup.ref],
                },
              ],
            },
            {
              op: 'replace',
              path: '/providers/github/overrides/spec/actions/oidc/useDefault',
              value: true,
            },
            {
              op: 'replace',
              path: '/providers/github/overrides/spec/actions/oidc/includeClaimKeys',
              value: [],
            },
          ],
        },
      );

      await applyAndWaitCrPaths(client, renderedComponent.crPaths);

      await expect(client.gh.repoExists(componentName)).resolves.toBe(true);
      await expect(readCodeownersFile(client, componentName)).resolves.toEqual(
        buildExpectedCodeowners(
          client.getOrg(),
          defaultGroup.name,
          platformGroupName,
        ),
      );
    },
    LOCAL_RENDER_APPLY_TEST_TIMEOUT_MS,
  );
});
