dispatches:
  - type: snapshots
    flavors:
      - full-aws
    state_repos:
      - repo: state
        dispatch_event_type: "new-dispatch-image"
        base_path: ""
        tenant: prefapp
        application: firestartr
        env: dev
        service_names: ['controller']
        version: $branch_main
