import * as path from 'node:path';

import Ajv from 'ajv';
import type { ErrorObject } from 'ajv';

import { isFile, slurpFile } from './common';
import log from './logger';
import { formatAjvErrors } from './auxiliar';

/**
 * Validates user-supplied feature args against the feature's on-disk
 * `schema.json` (generated by prefapp/features from the feature's config.yaml).
 *
 * This is the validation body only: the caller owns the opt-in gate and must
 * check `isFeatureArgsValidationEnabled(configData)` first, since a feature
 * validates its args only when its config.yaml sets `enable_validation: true`.
 *
 * The downloader-injected `traceability` key is stripped before validation so it
 * never trips the unknown-key check. `additionalProperties: false` is injected
 * into a shallow copy of the schema before compiling; the on-disk file is never
 * mutated. A feature that ships no schema skips validation with a warning so
 * legacy, `ref`-fetched, and template features keep rendering.
 *
 * @param featurePath - Absolute path to the extracted feature.
 * @param featureArgs - The raw user-supplied feature args.
 */
export function validateFeatureArgs(
  featurePath: string,
  featureArgs: any,
): void {
  const schemaPath = path.join(featurePath, 'schema.json');

  if (!isFile(schemaPath)) {
    log.warn(
      `Feature ${featurePath} has no schema.json; skipping feature args validation`,
    );
    return;
  }

  let schema: Record<string, unknown>;
  try {
    schema = JSON.parse(slurpFile(schemaPath));
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(
      `Feature: loading schema.json at "${schemaPath}": ${message}`,
    );
  }

  const argsToValidate: any = { ...featureArgs };
  delete argsToValidate['traceability'];

  const ajv = new Ajv({ allErrors: true, strictSchema: false });
  const validate = ajv.compile({ ...schema, additionalProperties: false });

  if (validate(argsToValidate)) {
    return;
  }

  const lines = (validate.errors ?? []).map((error) => {
    const key = resolveOffendingKey(error);
    const where = key ? `/${key}` : '/';
    const value = key ? argsToValidate[key] : argsToValidate;
    return `${formatAjvErrors([{ ...error, instancePath: where }])} (got ${JSON.stringify(value)})`;
  });

  throw new Error(
    `Feature args invalid for "${featurePath}":\n${lines.join('\n')}`,
  );
}

function resolveOffendingKey(error: ErrorObject): string | undefined {
  if (typeof error.params?.additionalProperty === 'string') {
    return error.params.additionalProperty;
  }

  if (error.instancePath) {
    return error.instancePath.replace(/^\//, '');
  }

  return undefined;
}
