import { resolveClaimRef } from '../refresolver';
import common from 'catalog_common';

const CLAIM_KIND_TO_CR_KIND: Record<string, string> = {
  GroupClaim: 'FirestartrGithubGroup',
  UserClaim: 'FirestartrGithubMembership',
};

function fallbackResolveClaimRef(kind: string, name: string, crs?: any): any {
  if (!crs) {
    throw new Error(`Claim ${kind}-${name} not found`);
  }

  const expectedRef = `${kind}/${name}`;
  const claimRefAnnotation =
    common.generic.getFirestartrAnnotation('claim-ref');

  // Fast path: direct key lookup, but only trust it when the CR's
  // claim-ref annotation confirms the identity.
  const crKind = CLAIM_KIND_TO_CR_KIND[kind] || kind;
  const directLookup = crs[`${crKind}-${name}`] || crs[`${kind}-${name}`];
  if (directLookup) {
    const claimRef = (directLookup as any).metadata?.annotations?.[
      claimRefAnnotation
    ];
    if (claimRef === expectedRef) {
      return directLookup;
    }
  }

  // Fallback: scan crs by firestartr.dev/claim-ref annotation.
  // This handles the importer case where crs are keyed by metadata.name
  // (e.g. "group-b-abc123") but we're looking up by claim name ("group_b").
  for (const cr of Object.values(crs)) {
    const claimRef = (cr as any).metadata?.annotations?.[claimRefAnnotation];
    if (claimRef === expectedRef) {
      return cr;
    }
  }

  return undefined;
}

/**
 * @description This method creates a permission for a given claimRef and permission
 *
 * @param claimRef 'user:<username>' or 'group:<groupname>'
 *
 * @param permission 'admin' | 'push' | 'pull' | 'maintain'
 *
 * @returns Permission
 */
export function createPermissionFor(
  claimRef: `group:${string}` | `user:${string}` | `collaborator:${string}`,

  permission: 'admin' | 'push' | 'pull' | 'maintain',

  crs?: any,
): Permission | CollaboratorPermission {
  const splittedRef = claimRef.split(':');

  const owner = splittedRef[1];

  const kind = splittedRef[0];

  if (kind !== 'collaborator') {
    const kindForRef =
      kind === 'user' ? 'FirestartrGithubMembership' : 'FirestartrGithubGroup';

    const claimKind =
      kindForRef === 'FirestartrGithubGroup' ? 'GroupClaim' : 'UserClaim';

    let resolvedDependency: any;
    try {
      resolvedDependency = resolveClaimRef(claimKind, owner);
    } catch (e) {
      resolvedDependency = fallbackResolveClaimRef(claimKind, owner, crs);
      if (!resolvedDependency) throw e;
    }

    return {
      role: permission,

      ref: {
        kind: kindForRef,

        name: resolvedDependency.metadata.name,

        needsSecret: kind === 'group' ? true : false,
      },
    };
  } else {
    return {
      role: permission,

      collaborator: owner,
    };
  }
}

/**
 * @description This method creates a list of permissions for a given claimRefs and permission
 *
 * @param claimRefs 'user:<username>' or 'group:<groupname>'
 *
 * @param permission 'admin' | 'push' | 'pull' | 'maintain'
 *
 * @returns Permission[]
 */
export function createPermissionsListFor(
  claimRefs: (
    | `group:${string}`
    | `user:${string}`
    | `collaborator:${string}`
  )[],

  permission: 'admin' | 'push' | 'pull' | 'maintain',

  crs?: any,
): (Permission | CollaboratorPermission)[] {
  const permissions: (Permission | CollaboratorPermission)[] = [];

  for (const claimRef of claimRefs) {
    permissions.push(createPermissionFor(claimRef, permission, crs));
  }

  return permissions;
}
export function createCRrefFrom(
  claimRef: `group:${string}` | `user:${string}` | `collaborator:${string}`,
  needsSecret: boolean,
) {
  const splittedRef = claimRef.split(':');

  const owner = splittedRef[1];

  const kind = splittedRef[0];

  const kindForRef =
    kind === 'user' ? 'FirestartrGithubMembership' : 'FirestartrGithubGroup';

  return {
    ref: {
      kind: kindForRef,

      name: owner,

      needsSecret,
    },
  };
}

export interface Permission {
  role: 'admin' | 'push' | 'pull' | 'maintain';

  ref: {
    kind: 'FirestartrGithubMembership' | 'FirestartrGithubGroup';

    name: string;

    needsSecret: boolean;
  };
}

export interface CollaboratorPermission {
  role: 'admin' | 'push' | 'pull' | 'maintain';

  collaborator: string;
}

/**
 * @description This method creates the codeowners data for the repository
 *
 * @param claim
 *
 * @returns string
 */
export function createCodeOwnersData(
  claim: any,
  additionalRules?: any[],
  crs?: any,
): string {
  const rulesMap = new Map<string, string[]>();

  const addOwnerToPath = (path: string, owner: string) => {
    const owners = rulesMap.get(path) ?? [];

    if (!owners.includes(owner)) {
      owners.push(owner);
    }

    rulesMap.set(path, owners);
  };

  let message = `# This file was generated by firestartr.
# WARNING: Please don't edit this file directly in the repository
# Go to gitops repository to modify it!`;

  if (claim.owner) {
    addOwnerToPath(
      '*',
      resolveCodeownersRef(claim.owner, claim.providers.github.org, crs),
    );
  }

  if (claim.platformOwner) {
    addOwnerToPath(
      '/.github/',
      resolveCodeownersRef(
        claim.platformOwner,
        claim.providers.github.org,
        crs,
      ),
    );
  }

  if (additionalRules) {
    for (const rule of additionalRules) {
      for (const owner of rule.owners) {
        addOwnerToPath(
          rule.path,
          resolveCodeownersRef(owner, claim.providers.github.org, crs),
        );
      }
    }
  }

  for (const [path, owners] of rulesMap.entries()) {
    message += `\n${path.padEnd(25)} ${owners.join(' ')}`;
  }

  return message;
}

export function resolveCodeownersRef(ref: string, org: string, crs?: any) {
  let result = '';

  const splittedRef = ref.split(':');

  if (splittedRef.length !== 2) {
    throw new Error(`Invalid codeowners ref ${ref}`);
  }

  if (!['user', 'group'].includes(splittedRef[0])) {
    throw new Error(
      `Invalid codeowners ref ${ref}, kind must be "user" or "group"`,
    );
  }

  const owner = splittedRef[1];

  const kind = splittedRef[0];

  const claimKind = kind === 'user' ? 'UserClaim' : 'GroupClaim';

  let resolvedDependency: any;
  try {
    resolvedDependency = resolveClaimRef(claimKind, owner);
  } catch (e) {
    resolvedDependency = fallbackResolveClaimRef(claimKind, owner, crs);
    if (!resolvedDependency) throw e;
  }

  const annotations = resolvedDependency.metadata.annotations || {};

  const githubSlugAnnotation =
    common.generic.getFirestartrAnnotation('github-slug');
  const githubSlugValue = annotations[githubSlugAnnotation];

  let handle: string;
  if (githubSlugValue) {
    handle = githubSlugValue;
  } else {
    const claimRefAnnotation =
      common.generic.getFirestartrAnnotation('claim-ref');
    const claimRefValue = annotations[claimRefAnnotation];

    if (!claimRefValue || !claimRefValue.includes('/')) {
      throw new Error(
        `CR for ${ref} is missing firestartr.dev/claim-ref annotation`,
      );
    }

    handle = claimRefValue.split('/')[1];
  }

  if (kind === 'user') {
    result = `@${handle}`;
  } else if (kind === 'group') {
    result = `@${org}/${handle}`;
  }

  return result;
}

/**
 * A reference to a secret, which can be an internal or external source.
 */
export interface SecretRef {
  kind: 'Secret' | 'ExternalSecret';
  name: string;
  key: string;
}

/**
 *  * A variable definition. It must have a name and can be either a literal
 *   * value or a reference to a secret.
 *    */
export type Var =
  | {
      name: string;
      value: string;
    }
  | {
      name: string;
      ref: SecretRef;
    };

export type RepoSecret = {
  name: string;
  ref: RepoSecretRef;
};

export type NamedVars = Var[];

export type RepoSecrets = RepoSecret[];

export interface VarsConfiguration {
  actions?: NamedVars;
}

export interface RepoSecretsConfiguration {
  dependabot?: RepoSecrets;
  actions?: RepoSecrets;
  codespaces?: RepoSecrets;
}

const IS_SECRET_REF = new RegExp(
  /^ref:secretsclaim:([a-zA-Z0-9_-]+):([a-zA-Z0-9_-]+)$/,
);

// Match the union type defined elsewhere in your codebase
export interface RepoSecretRef {
  kind: 'secretsclaim';
  name: string;
  key: string;
}

export function isRepoSecretRef(suspectedRef: string) {
  return IS_SECRET_REF.test(suspectedRef);
}

export function extractRepoSecretRef(ref: string): RepoSecretRef {
  if (!IS_SECRET_REF.test(ref)) {
    throw new Error(`extractRepoSecretRef: ref not valid ${ref}`);
  }

  const parts = ref.split(':');

  const secretKind = parts[1];
  if (secretKind !== 'secretsclaim') {
    throw new Error(`extractRepoSecretRef: Invalid secret kind ${secretKind}`);
  }

  return {
    kind: secretKind as 'secretsclaim',
    name: parts[2],
    key: parts[3],
  };
}
