// Generated by src/codegen/generateCommands.ts. Do not edit.
export const CLAIM_KINDS = {
  ArgoDeployClaim: {
    id: 'argodeploy',
    icon: { emoji: '🚀', ascii: '[ARG]' },
    summary: 'Deploy an application to Argo CD from a claim.',
  },
  ComponentClaim: {
    id: 'component',
    icon: { emoji: '🧩', ascii: '[CMP]' },
    summary: 'Describe a software component and the repository that hosts it.',
  },
  DomainClaim: {
    id: 'domain',
    icon: { emoji: '🌐', ascii: '[DOM]' },
    summary: 'Describe a domain that groups related systems and components.',
  },
  GroupClaim: {
    id: 'group',
    icon: { emoji: '👥', ascii: '[GRP]' },
    summary: 'Manage a GitHub team and its membership.',
  },
  OrgSettingsClaim: {
    id: 'orgsettings',
    icon: { emoji: '🏢', ascii: '[ORG]' },
    summary: 'Configure GitHub organization settings and variables.',
  },
  OrgWebhookClaim: {
    id: 'orgwebhook',
    icon: { emoji: '🪝', ascii: '[WHK]' },
    summary: 'Configure a webhook for a GitHub organization.',
  },
  SecretsClaim: {
    id: 'secrets',
    icon: { emoji: '🔑', ascii: '[SEC]' },
    summary: 'Manage external secrets for a platform resource.',
  },
  SystemClaim: {
    id: 'system',
    icon: { emoji: '🏗️', ascii: '[SYS]' },
    summary: 'Describe a system made up of related components.',
  },
  TFWorkspaceClaim: {
    id: 'tfworkspace',
    icon: { emoji: '🧱', ascii: '[TFW]' },
    summary: 'Manage a Terraform workspace and its infrastructure state.',
  },
  UserClaim: {
    id: 'user',
    icon: { emoji: '👤', ascii: '[USR]' },
    summary: "Manage a GitHub user's organization membership.",
  },
} as const;

export type ClaimKindName = keyof typeof CLAIM_KINDS;
