// Generated by src/codegen/generateCommands.ts. Do not edit.
export const CLAIM_KINDS = {
  ArgoDeployClaim: { emoji: '🚀', ascii: '[ARG]' },
  ComponentClaim: { emoji: '🧩', ascii: '[CMP]' },
  DomainClaim: { emoji: '🌐', ascii: '[DOM]' },
  GroupClaim: { emoji: '👥', ascii: '[GRP]' },
  OrgSettingsClaim: { emoji: '🏢', ascii: '[ORG]' },
  OrgWebhookClaim: { emoji: '🪝', ascii: '[WHK]' },
  SecretsClaim: { emoji: '🔑', ascii: '[SEC]' },
  SystemClaim: { emoji: '🏗️', ascii: '[SYS]' },
  TFWorkspaceClaim: { emoji: '🧱', ascii: '[TFW]' },
  UserClaim: { emoji: '👤', ascii: '[USR]' },
} as const;

export type ClaimKindName = keyof typeof CLAIM_KINDS;
