---
# FEATURE_NAME: build_and_dispatch_docker_images
# FEATURE_VERSION: build_and_dispatch_docker_images-v5
# FEATURE_URL: https://github.com/prefapp/features/tree/build_and_dispatch_docker_images-v5/packages/build_and_dispatch_docker_images
# FEATURE_GIT_SHA: "b4db429cdc80af8e1a72cfef34762348f83adb37"
# FEATURE_GIT_TAGS: ["build_and_dispatch_docker_images-v5.7.2","build_and_dispatch_docker_images-v5"]

name: Build Docker releases
run-name: Generating releases images for flavors "${{ inputs.flavors || 'auto-build' }}" at "${{ inputs.from || github.event.release.tag_name }}"

concurrency:
  group: ${{ github.workflow }}-${{ inputs.from || github.event.release.tag_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      from:
        type: string
        description: Git tag to build
        required: false
      flavors:
        type: string
        description: Flavor name/s | one (alone), several (separated by commas)
        required: true
        default: "*"

  release:
    types: [released]

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build-amd64:
    uses: ./.github/workflows/build_images_reusable.yaml
    with:
      type: releases
      from: ${{ inputs.from || github.event.release.tag_name }}
      flavors: ${{ inputs.flavors || '' }}
      auth_strategy: ghcr
      check_run_name: 'Firestartr Docker Images Summary'
      workflows_repo: prefapp/firestarter-workflows
      workflows_repo_ref: v3
      platforms: "linux/amd64"
      runs_on: ${{ vars.BUILD_DOCKER_IMAGES_AMD64_RUNS_ON || '["ubuntu-24.04"]' }}
    secrets: inherit

  build-arm64:
    if: ${{ vars.BUILD_DOCKER_IMAGES_ARM64_RUNS_ON }}
    needs: [ build-amd64 ] # Ensure the arm64 build starts after the amd64 build
    uses: ./.github/workflows/build_images_reusable.yaml
    with:
      type: releases
      from: ${{ inputs.from || github.event.release.tag_name }}
      flavors: ${{ inputs.flavors || '' }}
      auth_strategy: ghcr
      check_run_name: 'Firestartr Docker Images Summary'
      workflows_repo: prefapp/firestarter-workflows
      workflows_repo_ref: v3
      platforms: "linux/arm64"
      runs_on: ${{ vars.BUILD_DOCKER_IMAGES_ARM64_RUNS_ON }}
    secrets: inherit

  summary:
    needs: [build-amd64, build-arm64]
    uses: ./.github/workflows/build_images_summary_reusable.yaml
    if: ${{
        always() && (
          needs.build-amd64.result != 'skipped' ||
          needs.build-arm64.result != 'skipped'
        )
      }}
    with:
      from: ${{ inputs.from || github.event.release.tag_name }}
      conclusion: ${{ (needs.build-amd64.result == 'success' || needs.build-arm64.result == 'success') && 'success' || 'failure' }}
      check_run_name: 'Firestartr Docker Images Summary'
    secrets:
      FS_CHECKS_PEM_FILE: "${{ secrets.FS_CHECKS_PEM_FILE }}"
