---
# FEATURE_NAME: build_and_dispatch_docker_images
# FEATURE_VERSION: build_and_dispatch_docker_images-v6
# FEATURE_URL: https://github.com/prefapp/features/tree/build_and_dispatch_docker_images-v6/packages/build_and_dispatch_docker_images
# FEATURE_GIT_SHA: "2cf4c2292479e548ab620cf168bbe11567cc62fb"
# FEATURE_GIT_TAGS: ["build_and_dispatch_docker_images-v6.0.0","build_and_dispatch_docker_images-v6"]

name: Trigger dispatches on pre-releases
run-name: Trigger dispatches on new pre-releases built at "${{ github.event.workflow_run.head_sha }}"

on:
  workflow_run:
    workflows: ["Build Docker pre-releases"]
    types:
      - completed

permissions:
  actions: write
  contents: read

jobs:
  on-success:
    runs-on: ubuntu-24.04
    if: ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event == 'release' &&
        github.event.workflow_run.head_repository.full_name == github.repository
      }}
    steps:
      - name: Dispatch image changes to state repos
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          set -euo pipefail
          echo 'The triggering workflow passed'
          gh workflow run make_dispatches.yaml -R "$REPOSITORY" \
          -f image_type=snapshots \
          -f flavors='*' \
          -f filter_by_env="pre" \
          -f workflow_run_id="$RUN_ID"
